// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Hono Server
 *
 * Auto-generated by @shogo-ai/sdk
 * This file can be customized - it will not be overwritten if it exists.
 */

import { Hono } from 'hono'
import { serveStatic } from 'hono/bun'
import customRoutes from './custom-routes'
import { createToolsHandlers } from '@shogo-ai/sdk/tools/server'

const app = new Hono()

// CORS — manual middleware so the wildcard always propagates
app.use('*', async (c, next) => {
  c.res.headers.set('Access-Control-Allow-Origin', '*')
  c.res.headers.set('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS')
  c.res.headers.set('Access-Control-Allow-Headers', 'Content-Type,Authorization')
  if (c.req.method === 'OPTIONS') return c.text('', 204)
  await next()
})

// Health check endpoint
app.get('/health', (c) => c.json({ ok: true, timestamp: new Date().toISOString() }))

// SHOGO:CUSTOM-START connection-routes
// Custom API routes mounted FIRST so sub-paths like /api/connections/providers
// aren't captured by CRUD's /:id catch-all
app.route('/api', customRoutes)
// SHOGO:CUSTOM-END

// CRUD routes (available after schema.prisma has models)
try {
  const { createAllRoutes } = await import('./src/generated')
  const { prisma } = await import('./src/lib/db')
  app.route('/api', createAllRoutes(prisma))
} catch {
  // No generated routes yet — CRUD routes will appear after schema.prisma is written
}

// Installed-integration tools proxy → forwards to the agent runtime
// using RUNTIME_AUTH_SECRET + RUNTIME_PORT (auto-detected from env).
const tools = createToolsHandlers({})
app.post('/api/tools/execute', (c) => tools.execute(c.req.raw))
app.get('/api/tools/schemas', (c) => tools.list(c.req.raw))

// Serve static files in production
app.use('/*', serveStatic({ root: './dist' }))
app.get('*', serveStatic({ path: './dist/index.html' }))

const port = Number(process.env.PORT) || 3001
console.log(`🚀 Server running on http://localhost:${port}`)

Bun.serve({ port, fetch: app.fetch })
